---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.23.3-bullseye

inputs:
  - name: s3crypto
    path: s3crypto

run:
  path: s3crypto/ci/scripts/build.sh
